export const expLists = [
  {
    id: 1,
    projectName: "iService",
    companyName: "Thailife Insurance Public Company Ltd",
    position: "Software Engineer",
    companyColor: "blue.500",
    frontend: "Next JS",
    backend: "Java Spring Boot",
    devops: "CI/CD Jenkins",
    database: "Postgres",
    year: "July 2022 - Present",
    description:
      "Working with internal project (Gathering all services into one service), In this project I've design and develop frontend application using Next JS and connect API with Java spring boot, in Backend section is RESTful API, and deployment with jenkins CI/CD",
  },
  {
    id: 2,
    projectName: "Internal Project",
    companyName: "Thailife Insurance Public Company Ltd",
    position: "Software Engineer",
    companyColor: "blue.500",
    frontend: "Next JS",
    backend: "Java Spring Boot",
    devops: "CI/CD Jenkins",
    database: "Postgres",
    year: "July 2022 - July 2022",
    description:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.",
  },
  {
    id: 3,
    projectName: "Prithailand",
    companyName: "Swiftlet Co Ltd",
    position: "Software Engineer",
    companyColor: "red.500",
    frontend: "React JS",
    backend: "Ruby On Rails",
    devops: "Docker",
    database: "Postgres",
    year: "June 2021 - May 2022",
    description:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.",
  },
  {
    id: 4,
    projectName: "BI Suite",
    companyName: "Swiftlet Co Ltd",
    position: "Software Engineer",
    companyColor: "red.500",
    frontend: "Next JS",
    backend: "Python",
    devops: "Docker",
    database: "Postgres",
    year: "Mar 2021 - Apr 2021",
    description:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.",
  },
  {
    id: 5,
    projectName: "Chat SmartFarmer",
    companyName: "Swiftlet Co Ltd",
    position: "Software Engineer",
    companyColor: "red.500",
    frontend: "Flutter (Mobile)",
    backend: "",
    devops: "",
    database: "",
    year: "Nov 2020 - Feb 2021",
    description:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.",
  },
  {
    id: 6,
    projectName: "KU Terebinth AWS Project",
    companyName: "Swiftlet Co Ltd",
    position: "Software Engineer / Devops",
    companyColor: "red.500",
    frontend: "",
    backend: "",
    devops: "Amazon Web Service EKS",
    database: "",
    year: "Oct 2020 - Nov 2020",
    description:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.",
  },
  {
    id: 7,
    projectName: "Terebinth ERP",
    companyName: "Swiftlet Co Ltd",
    position: "Software Engineer",
    companyColor: "red.500",
    frontend: "React js",
    backend: "Ruby On Rails",
    devops: "",
    database: "Mongo DB",
    year: "Mar 2019 - Sep 2020",
    description:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.",
  },
  {
    id: 8,
    projectName: "Ardala",
    companyName: "Swiftlet Co Ltd",
    position: "Software Engineer",
    companyColor: "red.500",
    frontend: "Vue js",
    backend: "Ruby On Rails",
    devops: "",
    database: "Mongo DB",
    year: "Sep 2018 - Feb 2019",
    description:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.",
  },
  {
    id: 9,
    projectName: "Schoolbus Tracker",
    companyName: "Swiftlet Co Ltd",
    position: "Software Engineer",
    companyColor: "red.500",
    frontend: "Jquery",
    backend: "Ruby On Rails",
    devops: "",
    database: "Mongo DB",
    year: "Mar 2018 - Aug 2018",
    description:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.",
  },
  {
    id: 10,
    projectName: "10DK",
    companyName: "Swiftlet Co Ltd",
    position: "Software Engineer",
    companyColor: "red.500",
    frontend: "Angular JS",
    backend: "Ruby On Rails",
    devops: "",
    database: "Mongo DB",
    year: "Jan 2018 - Feb 2018",
    description:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.",
  },
  {
    id: 11,
    projectName: "Schoolbus Tracker",
    companyName: "Swiftlet Co Ltd",
    position: "Software Engineer",
    companyColor: "red.500",
    frontend: "Jquery",
    backend: "Ruby On Rails",
    devops: "",
    database: "Mongo DB",
    year: "Aug 2017 - Dec 2017",
    description:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.",
  },
];
